name: macOS CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install SDL2 and dylibbundler
      run: |
           brew install sdl2
           brew install dylibbundler
    - name: Build and pack PSXE
      run: |
           git fetch --all --tags
           ./build.sh
           tar -czf psxe-macos-latest.tar.gz psxe.app
    - uses: actions/upload-artifact@v4
      with:
        name: psxe-macos-latest
        path: ./psxe-macos-latest.tar.gz
