name: Ubuntu CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: |
           sudo apt update
           sudo apt install libsdl2-dev
    - name: Build PSXE
      run: |
           make
    - name: Change executable permissions
      run:
           chmod +x ./bin/psxe
    - name: Pack executable
      run:
           tar -czf psxe-ubuntu-latest.tar.gz ./bin/psxe
    - uses: actions/upload-artifact@v3
      with:
        name: psxe-ubuntu-latest
        path: ./psxe-ubuntu-latest.tar.gz