name: Windows CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run build-deps
      run: ./build-deps.ps1
    - name: Run build-win64
      run: |
           ./build-win64.ps1
           New-Item -Path "psxe" -ItemType Directory
           Copy-Item -Recurse "bin" -Destination "psxe"
    - uses: actions/upload-artifact@v4
      with:
        name: psxe-win64-latest
        path: psxe/